In [93]:
import optuna
import pandas as pd

In [101]:
variable = "air"
state = 6
study = optuna.load_study(
    study_name=f"optimizing_parameters_{variable}_{state}_pareto",
    storage=f"sqlite:///optimize/db/optimizing_parameters_state_{state}_pareto.db",
)

In [102]:
df = study.trials_dataframe()
df

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_alpha,params_kernel_size_h,params_kernel_size_w,params_learning_rate,system_attrs_nsga2:generation,state
0,0,1.075270e+00,2.077814e+00,2023-12-04 12:34:10.380712,2023-12-04 12:37:57.872879,0 days 00:03:47.492167,0.021548,3,3,0.000833,0,COMPLETE
1,1,1.485140e+06,4.929844e+12,2023-12-04 12:47:21.139295,2023-12-04 12:48:36.212514,0 days 00:01:15.073219,0.539730,3,2,0.007233,0,COMPLETE
2,2,inf,inf,2023-12-04 12:56:46.821732,2023-12-04 13:01:50.746490,0 days 00:05:03.924758,0.653166,4,3,0.006094,0,COMPLETE
3,3,1.284388e+00,2.993537e+00,2023-12-04 13:09:06.533506,2023-12-04 13:12:07.175064,0 days 00:03:00.641558,0.021064,2,2,0.000604,0,COMPLETE
4,4,7.629070e+00,1.032410e+02,2023-12-04 13:16:35.180908,2023-12-04 13:17:02.125635,0 days 00:00:26.944727,0.586190,4,2,0.002189,0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,1.177852e+00,2.511983e+00,2023-12-06 06:28:32.495637,2023-12-06 06:33:57.597489,0 days 00:05:25.101852,0.242043,3,2,0.000325,3,COMPLETE
196,196,1.259341e+00,2.712137e+00,2023-12-06 06:43:54.945896,2023-12-06 06:46:21.484678,0 days 00:02:26.538782,0.034939,4,3,0.001625,3,COMPLETE
197,197,1.057755e+00,2.001790e+00,2023-12-06 06:55:26.590789,2023-12-06 07:00:38.103660,0 days 00:05:11.512871,0.586509,2,3,0.000709,3,COMPLETE
198,198,1.313824e+00,3.187404e+00,2023-12-06 07:12:49.947591,2023-12-06 07:17:30.329525,0 days 00:04:40.381934,0.050583,2,2,0.000269,3,COMPLETE
199,199,1.174062e+00,2.508924e+00,2023-12-06 07:21:07.883292,2023-12-06 07:24:55.275791,0 days 00:03:47.392499,0.026039,2,4,0.000709,3,COMPLETE

In [103]:
df = df.sort_values(by=['values_0','duration',],
                    ascending=[True,False,])
df

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_alpha,params_kernel_size_h,params_kernel_size_w,params_learning_rate,system_attrs_nsga2:generation,state
162,162,1.000701,1.779511,2023-12-05 22:43:04.139580,2023-12-05 22:50:00.008943,0 days 00:06:55.869363,0.561517,4,4,0.000371,3,COMPLETE
193,193,1.004311,1.768752,2023-12-06 05:59:17.781791,2023-12-06 06:03:45.823445,0 days 00:04:28.041654,0.586509,3,3,0.000709,3,COMPLETE
28,28,1.018876,1.849842,2023-12-04 18:07:10.818120,2023-12-04 18:14:10.451312,0 days 00:06:59.633192,0.569991,4,4,0.000253,0,COMPLETE
151,151,1.042000,1.926792,2023-12-05 20:10:34.659962,2023-12-05 20:17:31.407416,0 days 00:06:56.747454,0.569991,4,4,0.000253,3,COMPLETE
137,137,1.045991,1.968380,2023-12-05 17:21:48.030558,2023-12-05 17:27:01.787162,0 days 00:05:13.756604,0.233696,3,3,0.000457,2,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...
2,2,inf,inf,2023-12-04 12:56:46.821732,2023-12-04 13:01:50.746490,0 days 00:05:03.924758,0.653166,4,3,0.006094,0,COMPLETE
39,39,inf,inf,2023-12-04 20:27:52.170621,2023-12-04 20:31:41.799906,0 days 00:03:49.629285,0.605102,2,4,0.007827,0,COMPLETE
38,38,inf,inf,2023-12-04 20:18:08.304911,2023-12-04 20:20:56.559375,0 days 00:02:48.254464,0.300575,3,3,0.007562,0,COMPLETE
84,84,inf,inf,2023-12-05 05:45:43.932981,2023-12-05 05:48:17.307087,0 days 00:02:33.374106,0.653166,2,3,0.006094,1,COMPLETE
46,46,inf,inf,2023-12-04 21:42:08.653387,2023-12-04 21:43:23.580383,0 days 00:01:14.926996,0.479127,2,3,0.008396,0,COMPLETE

In [105]:
study.best_trials

[FrozenTrial(number=162, state=TrialState.COMPLETE, values=[1.0007010698318481, 1.7795113325119019], datetime_start=datetime.datetime(2023, 12, 5, 22, 43, 4, 139580), datetime_complete=datetime.datetime(2023, 12, 5, 22, 50, 0, 8943), params={'kernel_size_w': 4, 'kernel_size_h': 4, 'alpha': 0.5615167370773423, 'learning_rate': 0.00037111909876522966}, user_attrs={}, system_attrs={'nsga2:generation': 3}, intermediate_values={}, distributions={'kernel_size_w': IntDistribution(high=4, log=False, low=2, step=1), 'kernel_size_h': IntDistribution(high=4, log=False, low=2, step=1), 'alpha': FloatDistribution(high=0.9, log=True, low=0.01, step=None), 'learning_rate': FloatDistribution(high=0.01, log=True, low=0.0001, step=None)}, trial_id=487, value=None),
 FrozenTrial(number=193, state=TrialState.COMPLETE, values=[1.004311442375183, 1.7687522172927856], datetime_start=datetime.datetime(2023, 12, 6, 5, 59, 17, 781791), datetime_complete=datetime.datetime(2023, 12, 6, 6, 3, 45, 823445), params={'kernel_size_w': 3, 'kernel_size_h': 3, 'alpha': 0.5865093853254476, 'learning_rate': 0.0007090378656413343}, user_attrs={}, system_attrs={'nsga2:generation': 3}, intermediate_values={}, distributions={'kernel_size_w': IntDistribution(high=4, log=False, low=2, step=1), 'kernel_size_h': IntDistribution(high=4, log=False, low=2, step=1), 'alpha': FloatDistribution(high=0.9, log=True, low=0.01, step=None), 'learning_rate': FloatDistribution(high=0.01, log=True, low=0.0001, step=None)}, trial_id=580, value=None)]

In [106]:
for std_trial in study._get_trials():
    if std_trial.number == 162:
        print(std_trial._trial_id, std_trial.values, std_trial.params)

487 [1.0007010698318481, 1.7795113325119019] {'kernel_size_w': 4, 'kernel_size_h': 4, 'alpha': 0.5615167370773423, 'learning_rate': 0.00037111909876522966}